Rebuilt workflows.

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -1,6 +1,6 @@
 # --------------------------------------------------------------------------------
-# This workflow was automatically generated by Action Status 1.0.2 (365).
-# (see https://actionstatus.elegantchaos.com for more details)
+# This workflow was automatically generated by ActionBuilderTool 1.0.
+# (see https://github.com/elegantchaos/ActionBuilderCore for more details)
 # --------------------------------------------------------------------------------
 
 name: Tests
@@ -9,10 +9,10 @@ on: [push, pull_request]
 
 jobs:
 
-    linux-swift-53:
-        name: Linux (Swift 5.3)
+    linux-swift56:
+        name: Linux (Swift 5.6)
         runs-on: ubuntu-18.04
-        container: swift:5.3.3-bionic
+        container: swift:5.6.2-bionic
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -20,10 +20,8 @@ jobs:
           run: mkdir logs
         - name: Swift Version
           run: swift --version
-        - name: Build (Release)
-          run: swift build -c release
-        - name: Test (Release)
-          run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Test (release)
+          run: swift test --configuration release -Xswiftc -enable-testing 
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
@@ -32,10 +30,10 @@ jobs:
             path: logs
 
 
-    linux-swift-nightly:
-        name: Linux (Swift Development Nightly)
+    linux-swift57:
+        name: Linux (Swift 5.7)
         runs-on: ubuntu-18.04
-        container: swiftlang/swift:nightly
+        container: swiftlang/swift:nightly-5.7-bionic
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -43,10 +41,8 @@ jobs:
           run: mkdir logs
         - name: Swift Version
           run: swift --version
-        - name: Build (Release)
-          run: swift build -c release
-        - name: Test (Release)
-          run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Test (release)
+          run: swift test --configuration release -Xswiftc -enable-testing 
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
@@ -55,9 +51,9 @@ jobs:
             path: logs
 
 
-    xcode-swift-53:
-        name: Xcode (Swift 5.3)
-        runs-on: macOS-latest
+    macOS-swift56:
+        name: macOS (Swift 5.6)
+        runs-on: macos-12
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -65,92 +61,14 @@ jobs:
           run: mkdir logs
         - name: Xcode Version
           run: |
-            sudo xcode-select -s /Applications/Xcode_12.3.app
+            ls -d /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_13.4.1.app
             xcodebuild -version
             swift --version
-        - name: XC Pretty
-          run: sudo gem install xcpretty-travis-formatter
-        - name: Detect Workspace & Scheme (macOS)
-          run: |
-            WORKSPACE="JSONSession.xcworkspace"
-            if [[ ! -e "$WORKSPACE" ]]
-            then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep JSONSession-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="JSONSession-Package"
-            else
-            SCHEME="JSONSession"
-            fi
-            else
-            SCHEME="JSONSession-macOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (macOS Release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-xcode-build-release.log | xcpretty
-        - name: Test (macOS Release)
-          run: |
-            source "setup.sh"
-            echo "Testing workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME"  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-xcode-test-release.log | xcpretty
-        - name: Detect Workspace & Scheme (iOS)
-          run: |
-            WORKSPACE="JSONSession.xcworkspace"
-            if [[ ! -e "$WORKSPACE" ]]
-            then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep JSONSession-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="JSONSession-Package"
-            else
-            SCHEME="JSONSession"
-            fi
-            else
-            SCHEME="JSONSession-iOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (iOS Release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
-        - name: Test (iOS Release)
-          run: |
-            source "setup.sh"
-            echo "Testing workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
-        - name: Detect Workspace & Scheme (tvOS)
-          run: |
-            WORKSPACE="JSONSession.xcworkspace"
-            if [[ ! -e "$WORKSPACE" ]]
-            then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep JSONSession-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="JSONSession-Package"
-            else
-            SCHEME="JSONSession"
-            fi
-            else
-            SCHEME="JSONSession-tvOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (tvOS Release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
-        - name: Test (tvOS Release)
-          run: |
-            source "setup.sh"
-            echo "Testing workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
+        - name: Swift Version
+          run: swift --version
+        - name: Test (release)
+          run: swift test --configuration release -Xswiftc -enable-testing 
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
@@ -159,11 +77,11 @@ jobs:
             path: logs
 
 
-    xcode-swift-nightly:
-        name: Xcode (Swift Development Nightly)
-        runs-on: macOS-latest
+    macOS-swift57:
+        name: macOS (Swift 5.7)
         env:
             TOOLCHAINS: swift
+        runs-on: macos-12
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -171,8 +89,8 @@ jobs:
           run: mkdir logs
         - name: Install Toolchain
           run: |
-            branch="development"
-            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            branch="swift-5.7-branch"
+            wget --quiet https://download.swift.org/$branch/xcode/latest-build.yml
             grep "download:" < latest-build.yml > filtered.yml
             sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
             sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
@@ -181,41 +99,41 @@ jobs:
             wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
             sudo installer -pkg $downloadYML-osx.pkg -target /
             ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
-            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            ls -d /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_13.4.1.app
             swift --version
         - name: Xcode Version
           run: |
             xcodebuild -version
             xcrun swift --version
+        - name: Swift Version
+          run: swift --version
+        - name: Test (release)
+          run: export PATH="swift-latest:$PATH"; swift test --configuration release -Xswiftc -enable-testing 
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    xcode-swift56:
+        name: iOS/tvOS/watchOS (Swift 5.6, Xcode 13.4.1)
+        runs-on: macos-12
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Xcode Version
+          run: |
+            ls -d /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_13.4.1.app
+            xcodebuild -version
+            swift --version
         - name: XC Pretty
           run: sudo gem install xcpretty-travis-formatter
-        - name: Detect Workspace & Scheme (macOS)
-          run: |
-            WORKSPACE="JSONSession.xcworkspace"
-            if [[ ! -e "$WORKSPACE" ]]
-            then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep JSONSession-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="JSONSession-Package"
-            else
-            SCHEME="JSONSession"
-            fi
-            else
-            SCHEME="JSONSession-macOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (macOS Release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-xcode-build-release.log | xcpretty
-        - name: Test (macOS Release)
-          run: |
-            source "setup.sh"
-            echo "Testing workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME"  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-xcode-test-release.log | xcpretty
         - name: Detect Workspace & Scheme (iOS)
           run: |
             WORKSPACE="JSONSession.xcworkspace"
@@ -233,11 +151,6 @@ jobs:
             SCHEME="JSONSession-iOS"
             fi
             echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (iOS Release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
         - name: Test (iOS Release)
           run: |
             source "setup.sh"
@@ -260,16 +173,138 @@ jobs:
             SCHEME="JSONSession-tvOS"
             fi
             echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (tvOS Release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
         - name: Test (tvOS Release)
           run: |
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (watchOS)
+          run: |
+            WORKSPACE="JSONSession.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep JSONSession-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="JSONSession-Package"
+            else
+            SCHEME="JSONSession"
+            fi
+            else
+            SCHEME="JSONSession-watchOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (watchOS release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 5 - 44mm" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    xcode-swift57:
+        name: iOS/tvOS/watchOS (Swift 5.7, Xcode 13.4.1)
+        env:
+            TOOLCHAINS: swift
+        runs-on: macos-12
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="swift-5.7-branch"
+            wget --quiet https://download.swift.org/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            ls -d /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_13.4.1.app
+            swift --version
+        - name: Xcode Version
+          run: |
+            xcodebuild -version
+            xcrun swift --version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (iOS)
+          run: |
+            WORKSPACE="JSONSession.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep JSONSession-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="JSONSession-Package"
+            else
+            SCHEME="JSONSession"
+            fi
+            else
+            SCHEME="JSONSession-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (iOS release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-build-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="JSONSession.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep JSONSession-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="JSONSession-Package"
+            else
+            SCHEME="JSONSession"
+            fi
+            else
+            SCHEME="JSONSession-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (tvOS release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
+        - name: Detect Workspace & Scheme (watchOS)
+          run: |
+            WORKSPACE="JSONSession.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep JSONSession-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="JSONSession-Package"
+            else
+            SCHEME="JSONSession"
+            fi
+            else
+            SCHEME="JSONSession-watchOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (watchOS release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 5 - 44mm" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
